geolessel/pco-dashboard

apps/dashboard/lib/dashboard/dashboards.ex, apps/dashboard/lib/dashboard/dashboards/component.ex, apps/dashboard/lib/dashboard/dashboards/dashboard.ex, apps/dashboard/lib/dashboard/dashboards/dashboard_component.ex, apps/dashboard/priv/repo/migrations/20200429043542_create_dashboard_components.exs, apps/dashboard/priv/repo/seeds.exs, apps/dashboard_web/lib/dashboard_web/live/components/forms_overview.ex, apps/dashboard_web/lib/dashboard_web/live/components/person_updated.ex, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/index.html.leex, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/layout.ex, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/layout.html.leex, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/show.ex, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/show.html.leex, apps/dashboard_web/lib/dashboard_web/router.ex
- Each component takes care of its own state
- Added a layout editor that allows the user to add or remove components to a layout
=> feature(Components): stateful components; configurable layouts

apps/dashboard/lib/dashboard/dashboards.ex, apps/dashboard/lib/dashboard/dashboards/dashboard_component.ex, apps/dashboard/priv/repo/migrations/20200429182639_add_sequence_to_dashboard_components.exs, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/layout.ex, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/layout.html.leex
- append a new DashboardComponent to the sequence (current max + 1)
- resequence later fields when a DashboardComponent is deleted
=> feat(sequencing): DashboardComponents can be sequenced

apps/dashboard/lib/dashboard/dashboards.ex, apps/dashboard_web/assets/css/app.scss, apps/dashboard_web/assets/css/draggable.css, apps/dashboard_web/assets/css/phoenix.css, apps/dashboard_web/assets/js/app.js, apps/dashboard_web/assets/js/dragAndDropComponents.js, apps/dashboard_web/assets/package-lock.json, apps/dashboard_web/assets/package.json, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/layout.ex, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/layout.html.leex, apps/dashboard_web/lib/dashboard_web/templates/layout/_user_menu.html.eex
I was hoping to make the database call a single `update_all`, but I think I was hitting race conditions when doing a `inc: [sequence: 1]` where lower sequenced components were being increased before the later ones. I could not reliably reproduce the error -- it was intermittent -- which is why I think it was a race condition. I could not reproduce it at all when updating the components' sequences one at a time in a specific direction.
=> feat(sortable): add drag and drop sortability!

apps/dashboard/lib/dashboard/dashboards.ex
The same issues that were popping up in resequencing after drag and
drop were starting to show up here. And again, instead of a single
`update_all` call, this splits the calls into as many `update` calls
as required.
=> fix: DashboardComponent deletion

apps/dashboard_web/lib/dashboard_web/live/dashboard_live/form_component.html.leex, apps/dashboard_web/lib/dashboard_web/live/modal_component.ex, apps/dashboard_web/lib/dashboard_web/templates/user_settings/edit.html.eex
Just some clean styles to make these usable again.
=> style: modal & settings

apps/dashboard_web/assets/css/app.scss, apps/dashboard_web/assets/stylelint.config.js, apps/dashboard_web/assets/tailwind.config.js, apps/dashboard_web/lib/dashboard_web/live/components/forms_overview.ex, apps/dashboard_web/lib/dashboard_web/live/components/person_updated.ex, apps/dashboard_web/lib/dashboard_web/templates/layout/table-card.html.leex
Tweaked the background color for the card title, other styles are the same, just consolidated.
=> style: classes for .card and .clean-table

apps/dashboard/priv/repo/seeds.exs, apps/dashboard_web/assets/css/app.scss, apps/dashboard_web/assets/tailwind.config.js, apps/dashboard_web/lib/dashboard_web/live/components/check_ins.ex, apps/dashboard_web/lib/dashboard_web/templates/layout/table-card.html.leex
Added a new table and the option to adjust widths. Woo!
=> feat: add CheckIns component

apps/dashboard/lib/dashboard/dashboards.ex, apps/dashboard/lib/dashboard/stores/component_store.ex, apps/dashboard_web/lib/dashboard_web/controllers/user_settings_controller.ex, apps/dashboard_web/lib/dashboard_web/live/components/check_ins.ex, apps/dashboard_web/lib/dashboard_web/live/components/forms_overview.ex, apps/dashboard_web/lib/dashboard_web/live/components/person_updated.ex, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/layout.ex
I don't like the warnings. Get rid of 'em.
=> chore: clean up things giving compile warnings

apps/dashboard/priv/repo/seeds.exs, apps/dashboard_web/lib/dashboard_web/live/component_helpers.ex, apps/dashboard_web/lib/dashboard_web/live/components/check_in_count.ex, apps/dashboard_web/lib/dashboard_web/live/components/check_ins.ex, apps/dashboard_web/lib/dashboard_web/live/components/forms_overview.ex, apps/dashboard_web/lib/dashboard_web/live/components/headcounts.ex, apps/dashboard_web/lib/dashboard_web/templates/layout/number-card.html.leex, apps/dashboard_web/lib/dashboard_web/templates/layout/table-card.html.leex
Added a couple of related components (Check-ins & Headcounts).
The data is mostly fudged as we don't currently have access to meta data. We'll need to add appropriate datetime filters eventually as well.
=> feat: NumberCard template

apps/dashboard_web/assets/css/app.scss, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/index.html.leex, apps/dashboard_web/lib/dashboard_web/views/error_helpers.ex
=> style: dashboard index

apps/dashboard/lib/dashboard/component.ex, apps/dashboard/lib/dashboard/components/profiles_created_over_week.ex, apps/dashboard/priv/repo/seeds.exs, apps/dashboard_web/lib/dashboard_web.ex, apps/dashboard_web/lib/dashboard_web/live/components/check_in_count.ex, apps/dashboard_web/lib/dashboard_web/live/components/headcounts.ex, apps/dashboard_web/lib/dashboard_web/live/components/person_updated.ex, apps/dashboard_web/lib/dashboard_web/live/components/profiles_created_over_week.ex, apps/dashboard_web/lib/dashboard_web/templates/layout/number-card.html.leex
This is the first multi-data-source component and is build mainly to
show how to create others in the future. It could be a useful
component on its own, I suppose...
=> feat: add ProfilesCreatedOverWeek component

apps/dashboard/lib/dashboard/component.ex
If no one is subscribed to a Component GenServer, it won't fetch the
api endpoint and it also won't update the `last_update` timestamp. If
there are no subscribers, and it's been more that 10 minutes since the
last listened-to update, terminate the GenServer. We can easily spin
it back up again when needed.
Satisfies #25.
=> change: terminate Component GenServers if no one's subscribed

apps/dashboard_web/assets/css/app.scss, apps/dashboard_web/assets/css/btn.scss, apps/dashboard_web/assets/css/card.scss, apps/dashboard_web/assets/css/clean-table.scss, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/index.html.leex, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/layout.html.leex, apps/dashboard_web/lib/dashboard_web/templates/layout/number-card.html.leex, apps/dashboard_web/lib/dashboard_web/templates/layout/table-card.html.leex
I styled everything mostly as is, but I feel like maybe we should eliminate the "Available Components" section and just use an `Add component` modal where you can select a component and add the config details. This would let us eventually have the "choose the component type, and then the data model (or vice versa)" contained in one place.
What do you think?
=> style: layout page

apps/dashboard_web/assets/css/draggable.css, apps/dashboard_web/assets/js/dragAndDropComponents.js, apps/dashboard_web/lib/dashboard_web/live/dashboard_live/layout.html.leex
This is a WIP as I simply hardcoded some numbers in the template, but it works! I'm still hitting the arrangement bug from https://github.com/geolessel/pco-dashboard/issues/27 and there's other jankiness, but as a concept it's working.
We _probably_ need to pass these values in a better way than I have here. 😆
=> feat: layout - use grid-sizes

apps/dashboard/lib/dashboard/dashboards/dashboard.ex
=> fix: add list of words unpermitted as slugs

apps/dashboard/lib/dashboard/component.ex
This is a pretty naive implementation, but it works for now. In the
future, looking deeper into Flow might be better.
=> change: make each component fetch api calls in parallel

apps/dashboard/lib/dashboard/components/check_in_count.ex, apps/dashboard/lib/dashboard/components/check_ins.ex, apps/dashboard/lib/dashboard/components/form_submissions.ex, apps/dashboard/lib/dashboard/components/forms_overview.ex, apps/dashboard/lib/dashboard/components/headcounts.ex, apps/dashboard/lib/dashboard/components/list_results.ex, apps/dashboard/lib/dashboard/components/person_updated.ex, apps/dashboard/lib/dashboard/components/profiles_created_over_time_chart.ex, apps/dashboard/lib/dashboard/components/profiles_created_over_week.ex, apps/dashboard/lib/planning_center_api/response.ex, apps/dashboard_web/lib/dashboard_web/live/components/form_submissions.ex, apps/dashboard_web/lib/dashboard_web/live/components/list_results.ex
I had originally planned on having the component have an attribute, but I think this might be better. At least for now. 😆
=> feat: Dynamic titles for FormSubmissions and ListResults

apps/dashboard_web/lib/dashboard_web/templates/layout/app.html.eex
=> style: flash messages

apps/dashboard/lib/api_client.ex, apps/dashboard/lib/dashboard/accounts.ex, apps/dashboard/lib/dashboard/component.ex, apps/dashboard/lib/planning_center_api/client.ex, apps/dashboard/lib/planning_center_api/oauth.ex, apps/dashboard_web/lib/dashboard_web/controllers/oauth_controller.ex
I can foresee a race condition here, but for now, let's get it out there.
=> feat: refresh oauth token if expired

apps/dashboard/lib/api_client.ex, apps/dashboard_web/assets/js/app.js, apps/dashboard_web/assets/package.json, apps/dashboard_web/assets/yarn.lock
- remove scgo-loader
- fix `pat` typo
- remove "general" Planning Center SVGs
=> chore: more cleanup

apps/dashboard_web/lib/dashboard_web/templates/layout/chart-card.html.leex, apps/dashboard_web/lib/dashboard_web/templates/layout/number-card.html.leex, apps/dashboard_web/lib/dashboard_web/templates/layout/table-card.html.leex
Clearly a lot of duplication here that could be cleaned up in a followup PR.
=> fix: cleanup css for proper purging

Dockerfile, apps/dashboard/lib/dashboard/component.ex, apps/dashboard/lib/release.ex, apps/dashboard_web/lib/dashboard_web/controllers/health_controller.ex, apps/dashboard_web/lib/dashboard_web/router.ex, config/config.exs, config/prod.exs, config/releases.exs, docker-compose.yml, mix.exs
prepare for release! This adds a Dockerfile and a docker-compose.yml file in order to make compiling, deploying, or just trying out the dashboard easier. I'm still a docker newb, so I'm sure my dockerfile could use some trimming down.
There is some missing docs for all this and I shall get to that shortly.
=> feat: release and docker

Dockerfile, config/releases.exs
- allow hostname/domain name to be set at runtime
- dockerfile: expose port 4000; correctly place lib files for web
=> change: release fixes and changes
